document.writeln("<!DOCTYPE html>");
document.writeln("<html xmlns=\"http://www.w3.org/1999/xhtml\">");
document.writeln("<head>");
document.writeln("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
document.writeln("    <title>top</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\"header\">");
document.writeln("        <div class=\"head clearfix\">");
document.writeln("            <div class=\"logo\"><a href=\"\"><img src=\"../../webCommon/images/top/logo.png\" alt=\"仪器\" /></a></div>");
document.writeln("            <div class=\"head_r\">");
document.writeln("                <div class=\"head_ra\">");
document.writeln("                    <div class=\"tel\">");
document.writeln("                        <span>咨询热线：</span>");
document.writeln("                        <b>15927107498</b>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <ul class=\"nav clearfix\">");
document.writeln("                    <li><a href=\"index.html\">首页</a></li>");
document.writeln("                    <li><a href=\"views/aboutUs/about.html\">关于我们</a></li>");
document.writeln("                    <li><a href=\"views/products/productList.html\">产品中心</a></li>");
document.writeln("                    <li><a href=\"views/news/newsList.html\">新闻资讯</a></li>");
document.writeln("                    <li><a href=\"views/jobs/jobs.html\">人才招聘</a></li>");
document.writeln("                    <li><a href=\"views/aboutUs/contact.html\">联系我们</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");